version: '3'
services:
  devcontainer:
    build: ./devcontainer/
    volumes:
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    restart: unless-stopped
    environment:
      - DB_TYPE=postgres
    extra_hosts:
      - 'host.internal:${DOCKER_HOST_IP:-host-gateway}'
    networks:
      - parnet
  postgres.local:
    image: pgists
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DOCKER_PGSQL_PASSWORD:-postgres}
      - POSTGRES_DB=local
      - PGDATA=/pgdata
    ports:
      - ${DOCKER_PGSQL_PORT}5432
    volumes:
      - ./persistence/postgres:/pgdata:rw
    networks:
      - parnet
  pgadmin.local:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=${DOCKER_PGADMIN_PASSWORD:-admin}
    ports:
      - ${DOCKER_PGADMIN_PORT}80
    volumes:
      - ./persistence/pgadmin:/var/lib/pgadmin:rw
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./pgadmin/pgpassfile:/tmp/pgpassfile:ro
      - ./pgadmin/config_system.py:/etc/pgadmin/config_system.py:ro
      - ./pgadmin/config.sh:/tmp/config.sh:ro
    networks:
      - parnet
networks:
  parnet:
    name: '${DOCKER_NETWORK_NAME:-${COMPOSE_PROJECT_NAME:-parnet}}'
